apiVersion: apps/v1
kind: Deployment
metadata:
  name: volunteer-service
  namespace: solidarytech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volunteer-service
  template:
    metadata:
      labels:
        app: volunteer-service
    spec:
      containers:
        - name: volunteer-service
          image: 354132155257.dkr.ecr.us-east-1.amazonaws.com/solidarytech-volunteer:ba5f145c3fc0f0dcb23ce21e80bf0fae7a2a489c
          ports:
            - containerPort: 8083
          env:
            - name: AWS_DYNAMODB_TABLE
              valueFrom:
                secretKeyRef:
                  name: volunteer-service-secret
                  key: AWS_DYNAMODB_TABLE
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: volunteer-service-secret
                  key: AWS_REGION
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: volunteer-service-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: volunteer-service-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: volunteer-service-secret
                  key: AWS_SESSION_TOKEN
            - name: OTEL_SERVICE_NAME
              value: "volunteer-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=production"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
